[package]
name = "ffi_bridge"
version = "0.1.0"
edition = "2021"

# This is crucial for creating a shared library
[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
aries-askar = "0.3.1"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
libc = "0.2"
