# Minimal analysis options
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Ignore all info-level issues
    avoid_print: ignore
    deprecated_member_use: ignore
    
linter:
  rules:
    # Disable strict rules
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
