[target.aarch64-linux-android]
ar = "/Users/itzmi/Library/Android/sdk/ndk/29.0.13113456/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "/Users/itzmi/Library/Android/sdk/ndk/29.0.13113456/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android34-clang"

[target.armv7-linux-androideabi]
ar = "/Users/itzmi/Library/Android/sdk/ndk/29.0.13113456/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "/Users/itzmi/Library/Android/sdk/ndk/29.0.13113456/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi34-clang"

[target.x86_64-linux-android]
ar = "/Users/itzmi/Library/Android/sdk/ndk/29.0.13113456/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "/Users/itzmi/Library/Android/sdk/ndk/29.0.13113456/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android34-clang"

[net]
git-fetch-with-cli = true
